version: '3.8'

services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - "27017:27017"
    volumes:
      - ./data/dump:/dump
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 192.168.33.10:8083/nodemongoapp:6.0
    container_name: back
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      MONGO_URI: mongodb://127.0.0.1:27017/EmergencyManagementSystemBD
    working_dir: /app
    command: npm run dev

volumes:
  mongo-data:
