services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - "27017:27017"
    volumes:
      - ./data/dump:/dump
      - mongo-data:/data/db

  app:
    image: anasbettouzia/nodemongoapp:6.0
    container_name: back
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      PORT: 3001
      MONGO_URI: mongodb://root:example@db:27017/EmergencyManagementSystemBD?authSource=admin
    working_dir: /app
    command: npm run dev

volumes:
  mongo-data:
